import { Table } from "antd";

export default function HistoryListPage() {
    // const dataSource = [
    //     {
    //         key: '1',
    //         name: '胡彦斌',
    //         age: 32,
    //         address: '西湖区湖底公园1号xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号',
    //     },
    //     {
    //         key: '2',
    //         name: '胡彦祖',
    //         age: 42,
    //         address: '西湖区湖底公园1号xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    //     },
    // ]
    const columns = [
        {
            title: '姓名',
            dataIndex: 'name',
            key: 'name',
        },
        {
            title: '年龄',
            dataIndex: 'age',
            key: 'age',
        },
        {
            title: '住址',
            dataIndex: 'address',
            key: 'address',
        },
    ]

    return <Table dataSource={[]} columns={columns}
        scroll={{ y: 'calc(100vh - 150px)' }}
        pagination={{
            pageSize: 50,
            showSizeChanger: false,
            simple: true,
            total: 150
        }} />
}